### ISSUE TITLE
ChainedDeconstruction

### ISSUE THREAD

**Issue by Sijko** [EtiamNullam/Etiam-ONI-Modpack#1]
Not working with farm tiles. when the last one from all marked for destruction gets deconstructed (one by one) the game crashes with NullReferenceException.

**Comment by EtiamNullam** [comment]
I can't replicate this behaviour. Farm tiles work fine to me, they shouldn't be affected by ChainedDeconstruction mod as it doesn't work by default for them ;)

Probably some other mod caused it, share the 'output_log.txt' if you want me to investigate.

**Comment by Sijko** [comment]
problem solved. sorry.
