### ISSUE TITLE
Gas Overlay not working for me

### ISSUE THREAD

**Issue by nirahiel** [EtiamNullam/Etiam-ONI-Modpack#13]
[output_log.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/5127432/output_log.txt)
Do you need the list of mods I'm using ?

**Comment by EtiamNullam** [comment]
Looks like it should be working. Show me how the gas overlay (F1) looks for you. Do you suspect any other mod to be fiddling with the overlay? Try running the game with only `Gas Overlay` mod enabled.

**Comment by nirahiel** [comment]
Ok give me a minute, i'll do that, then edit this comment.
EDIT : I don't know what I did, but now it works just fine, polluted oxygen shows as a brownish gas and CO2 appears black, so I guess it's all good ? 
If so, you can close the issue. (Even though there is still the window on the top right that gives the wrong indications regarding colors, the one named "oxygen overlay")

**Comment by EtiamNullam** [comment]
I never bothered with changing the legend so it should be like that. Sounds like overlay works fine for you.

I'll close the issue now. If the problem comes back let me know.
