### ISSUE TITLE
Chained Deconstruction

### ISSUE THREAD

**Issue by Tellik** [EtiamNullam/Etiam-ONI-Modpack#16]
Well it's been a bit since I last played/used this mod. It appears that now it applies to more than just ladders, but also tiles.

It kind of looks like there's a config file there, but I have no idea what syntax to use for it. Would you be able to provide a config file to restore the original chained deconstruction behavior? (I honestly feel like being able to deconstruct whole stretches of building tiles is a little too powerful.)

**Comment by EtiamNullam** [comment]
I understand it might appear to be too strong.

Config to make it work only with ladders:

```
[
  "Ladder"
]
```

If you want to add more, for example make wires work too:

```
[
  "Ladder",
  "Wire"
]
```

You need exact building name for it to be included. I find building names by decompiling the game but I'm sure you can find it somewhere around the web.

"*" (default) is special and it will allow all buildings to be chained.

**Comment by Tellik** [comment]
Thank you much. I'll play around with it and I should be able to get it from here.
