### ISSUE TITLE
Draggable UI Crashing Game After Last Update

### ISSUE THREAD

**Issue by TroublesomeCorvid** [EtiamNullam/Etiam-ONI-Modpack#17]
Simple as that.  I've tried loading the game with Draggable UI as the only active mod, but I still get the upsadaisie error message.

Included is the output log.  Hope this helps.

[Player.log](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/5601824/Player.log)

**Comment by EtiamNullam** [comment]
Sorry for late response but this crash was happening most likely because of game engine update. It should be working fine now since mod version 3.0+.

Let me know if you still experience it.

**Comment by EtiamNullam** [comment]
No more sightings of this issue since version 3.0, closing.
