### ISSUE TITLE
An Error with CustomTemperatureOverlay

### ISSUE THREAD

**Issue by KambiAlcaus** [EtiamNullam/Etiam-ONI-Modpack#20]
I encountered an error when I installed CustomTemperatureOverlay and loaded my game.
So I uninstalled all but CustomTemperatureOverlay mods , and I tried to generate new game as a test.
But still game kept crashing. The file attached to this mail is the log of 2nd attempt.

I'm not English native so I'm sorry if my mail  has any strange words.

[Player.log](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/6120572/Player.log)

**Comment by KambiAlcaus** [comment]
Sorry, the problem has solved.
I've heard mod updater is effective in some cases, and I found mod version was outdated.

**Comment by EtiamNullam** [comment]
Don't worry your English is fine ;)

Good to know you managed to fix it yourself and thanks for sharing the solution.

Closing the issue now.
