### ISSUE TITLE
Mod not loading.

### ISSUE THREAD

**Issue by Phantum** [EtiamNullam/Etiam-ONI-Modpack#21]
I'm not sure if this is a mod conflict, or something else, and don't have time to fully investigate as I'm catching a plane in 20 minutes, Here's the log file however: 

https://pastebin.com/Qbt05F5J

If you need anything else please let me know :)

**Comment by EtiamNullam** [comment]
Looks like same problem as in issue #5, it should not happen anymore, so I'm pretty sure you're getting wrong version of the mod from Steam Workshop. It's a common problem in this game but other games also suffer from it.

You can try unsubscribe, subscribe, maybe delete mod content but sometimes you will still get outdated mod. The easiest way is to simply use a mod: [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) by [peterhaneve](https://github.com/peterhaneve) as stated in [FAQ -> Game crashes with mod installed](https://github.com/EtiamNullam/Etiam-ONI-Modpack#game-crashes-with-mod-installed).

You can also [Check mod version](https://github.com/EtiamNullam/Etiam-ONI-Modpack#how-to-check-mod-version) to make sure that's the real issue. Also if nothing else helps you can download mod directly from GitHub.

Let me know if you need more help or if you solved the issue. Anyway I hope you will sort it out and thanks for submitting the issue.

**Comment by Phantum** [comment]
I’m out of town for a few days so I’ll try that when I’m back home, and keep you posted here.   Thanks :)

**Comment by EtiamNullam** [comment]
Let me know if you still can't solve it. In any other case - open a new issue. I'm closing it now.
