### ISSUE TITLE
MaterialColor crashes on build 460813

### ISSUE THREAD

**Issue by Calio-Templar** [EtiamNullam/Etiam-ONI-Modpack#22]
crashes on starting with big terra on DLC (not mod)

[Player.log](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/6349356/Player.log)

**Comment by Calio-Templar** [comment]
https://github.com/EtiamNullam/Etiam-ONI-Modpack/blob/4e6701df4c5584f1d81c0efb4018d111832f51e3/src/MaterialColor/Painter.cs#L96
commenting this elif gave me a working dll. All my knowledge to programming is hello world so im not sure there is better workaround..

**Comment by Calio-Templar** [comment]
#23 #23

**Comment by EtiamNullam** [comment]
Thank you for help!

Indeed it looks like `filteredTint` is gone from `FilteredStorage`. Apparently `filteredTint` field migrated from `FilteredStorage` to `TreeFilterable`.

It might be even more simple to access it but why it has to be different for DLC and base game? Sadly I think right now it requires different handling for each.

**Comment by EtiamNullam** [comment]
3c05b86 should fix the issue. Let me know if it does not.

**Comment by Calio-Templar** [comment]
new version works well glad i could be help
