### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by ElectronicsArchiver** [EtiamNullam/Etiam-ONI-Modpack#28]
<br>
<br>

<div align = center>

I've found that multiple GitHub ONI mod repositories 
were describing how to manually install mods, 
so I made a guide instead.

[Installation Guide]

Would you mind if I made a PR, replacing 
the instructions with a link to the guide?

</div>

<br>
<br>

[Installation Guide]: https://github.com/OpenModding/Installation/tree/main/Games/Oxygen%20Not%20Included

**Comment by dan-oak** [comment]
_<p align="center">sorry to interrupt you,<br>i'm not a maintainer,<br>but i just want to say,<br>that<br>i admire your aesthetic sense</p>_ :)

**Comment by ElectronicsArchiver** [comment]
@dan-oak Thanks~

Maybe you will this as well then:
https://github.com/MarkedDown

**Comment by EtiamNullam** [comment]
@ElectronicsArchiver:

I don't see any point in users having to enter another repository just to see the paths where to place mods. It also poses a risk that it might become obsolete or misleading in future.

You can submit a PR with information from your guide regarding manual installation directly in `README.md` to cover Linux and Mac.

Maybe I'll change my mind when your guide is more mature. Good luck.

**Comment by ElectronicsArchiver** [comment]
Sure
