### ISSUE TITLE
Chained Deconstruction: Crash

### ISSUE THREAD

**Issue by anthonyankrapp** [EtiamNullam/Etiam-ONI-Modpack#30]
Crashing since today's QOL updates.
[error.txt](https://github.com/EtiamNullam/Etiam-ONI-Modpack/files/11764011/error.txt)

**Comment by EtiamNullam** [comment]
Thank you for reporting it here!

Should be fixed in 71a71ae8bde287be1fc5fec4d39b18c4f13a915d. Actually mentioned wrong issue number in the commit message, sorry!
