### ISSUE TITLE
ChainedDeconstruction  Bug since U47-561558-5

### ISSUE THREAD

**Issue by KanapowyWojownik** [EtiamNullam/Etiam-ONI-Modpack#31]
Broke with the newest update; exact error below:

Exception while loading mod 1737893485.Steam at C:/Users/xxx/OneDrive/Documenten/Klei/OxygenNotIncluded/mods/Steam/1737893485.
HarmonyLib.HarmonyException: Ambiguous match for HarmonyMethod[(class=Deconstructable, methodname=TriggerDestroy, type=Normal, args=undefined)] ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.

**Comment by EtiamNullam** [comment]
Actually a duplicate of #30 but thanks anyway for reporting!
