### ISSUE TITLE
ChainedDestruction crash in 404823 public_testing

### ISSUE THREAD

**Issue by Zod-** [EtiamNullam/Etiam-ONI-Modpack#5]
I just tested out the public_testing branch in steam for the [new update](https://forums.kleientertainment.com/forums/topic/117353-new-update-in-testing-404823/) and ChainedDestruction seems to be crashing for me. 

I can't tell if this is an issue on my end because it says something about not being able access the dll.

[output_log.txt](https://gist.githubusercontent.com/Zod-/f5c3213e858d7bd7645fa04290cdd8b7/raw/5a5e140eda966e314f2ed4a8b4e2ab6759195c69/output_log.txt)

**Comment by EtiamNullam** [comment]
I have already noticed your issue on workshop and answered it there.

Looks like its a small breaking change coming in the upcoming patch.

I have fixed it in c0e17e969f694850680f6cedefa53513f5edf13e

Thanks again for noticing me before that change went live on the main branch. Let me know if there is anything else not right.

**Comment by Zod-** [comment]
Nice. Works for me.
